import { ReactNode } from 'react'
import './globals.css'
// eslint-disable-next-line camelcase
import { Bebas_Neue, Roboto, Dosis } from 'next/font/google'

const bebasNeue = Bebas_Neue({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700'],
})

const dosis = Dosis({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
})

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${bebasNeue.className} ${roboto.className} ${dosis.className} `}
      >
        {children}
      </body>
    </html>
  )
}
